[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables for Railway
[deploy.env]
GIT_PYTHON_REFRESH = "quiet"

# Service configuration
[service]
name = "wappa-docs"

# Automatic deployment on git push
[triggers]
main = true